name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Repo Visualizer
        # You may pin to the exact commit or the version.
        # uses: githubocto/repo-visualizer@d89437ae41087c95815abff164cc3d64b37f323a
        uses: githubocto/repo-visualizer@0.3.0
        with:
          # A path (relative to the root of your repo) to where you would like the diagram to live. For example: images/diagram.svg. Default: diagram.svg
          output_file: # optional
          # A list of paths to exclude from the diagram, separated by commas. For example: dist,node_modules
          excluded_paths: # optional
          # The maximum number of nested folders to show files within. Default: 9
          max_depth: # optional
